package io.legado.app.constant

object EventBus {
    const val MEDIA_BUTTON = "mediaButton"
    const val RECREATE = "RECREATE"
    const val UP_BOOK = "upBookToc"
    const val ALOUD_STATE = "aloud_state"
    const val TTS_PROGRESS = "ttsStart"
    const val TTS_DS = "ttsDs"
    const val BATTERY_CHANGED = "batteryChanged"
    const val TIME_CHANGED = "timeChanged"
    const val UP_CONFIG = "upConfig"
    const val OPEN_CHAPTER = "openChapter"
    const val AUDIO_SUB_TITLE = "audioSubTitle"
    const val AUDIO_STATE = "audioState"
    const val AUDIO_PROGRESS = "audioProgress"
    const val AUDIO_SIZE = "audioSize"
    const val AUDIO_SPEED = "audioSpeed"
    const val SHOW_RSS = "showRss"
    const val WEB_SERVICE = "webService"
    const val UP_DOWNLOAD = "upDownload"
    const val SAVE_CONTENT = "saveContent"
    const val CHECK_SOURCE = "checkSource"
    const val CHECK_SOURCE_DONE = "checkSourceDone"
    const val REPLACE_RULE_SAVE = "replaceRuleSave"
    const val TIP_COLOR = "tipColor"
}