package io.legado.app.constant

object PreferKey {
    const val versionCode = "versionCode"
    const val themeMode = "themeMode"
    const val hideStatusBar = "hideStatusBar"
    const val clickTurnPage = "clickTurnPage"
    const val clickAllNext = "clickAllNext"
    const val hideNavigationBar = "hideNavigationBar"
    const val precisionSearch = "precisionSearch"
    const val readAloudOnLine = "readAloudOnLine"
    const val readAloudByPage = "readAloudByPage"
    const val ttsSpeechRate = "ttsSpeechRate"
    const val ttsSpeechPer = "ttsSpeechPer"
    const val prevKey = "prevKeyCode"
    const val nextKey = "nextKeyCode"
    const val showRss = "showRss"
    const val bookshelfLayout = "bookshelfLayout"
    const val bookshelfSort = "bookshelfSort"
    const val recordLog = "recordLog"
    const val processText = "process_text"
    const val cleanCache = "cleanCache"
    const val saveTabPosition = "saveTabPosition"
    const val pageAnim = "pageAnim"
    const val readBookFont = "readBookFont"
    const val fontFolder = "fontFolder"
    const val backupPath = "backupUri"
    const val threadCount = "threadCount"
    const val webPort = "webPort"
    const val keepLight = "keep_light"
    const val webService = "webService"
    const val webDavUrl = "web_dav_url"
    const val webDavAccount = "web_dav_account"
    const val webDavPassword = "web_dav_password"
    const val webDavCreateDir = "webDavCreateDir"
    const val changeSourceLoadToc = "changeSourceLoadToc"
    const val chineseConverterType = "chineseConverterType"
    const val launcherIcon = "launcherIcon"
    const val textSelectAble = "selectText"
    const val lastBackup = "lastBackup"
    const val bodyIndent = "textIndent"
    const val shareLayout = "shareLayout"
    const val readStyleSelect = "readStyleSelect"
    const val systemTypefaces = "system_typefaces"
    const val readBodyToLh = "readBodyToLh"
    const val eInkMode = "isEInkMode"
    const val textFullJustify = "textFullJustify"
    const val autoReadSpeed = "autoReadSpeed"

    const val cPrimary = "colorPrimary"
    const val cAccent = "colorAccent"
    const val cBackground = "colorBackground"
    const val cBBackground = "colorBottomBackground"

    const val cNPrimary = "colorPrimaryNight"
    const val cNAccent = "colorAccentNight"
    const val cNBackground = "colorBackgroundNight"
    const val cNBBackground = "colorBottomBackgroundNight"

    const val cLPrimary = "lastColorPrimary"
    const val cLAccent = "lastColorAccent"
    const val cLBackground = "lastColorBackground"
    const val cLBBackground = "lastColorBottomBackground"

    const val lastPageAnim = "lastPageAnim"
    const val lastThemeMode = "lastThemeMode"
}