/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BookItems: typeof import('./components/BookItems.vue')['default']
    CatalogItem: typeof import('./components/CatalogItem.vue')['default']
    ChapterContent: typeof import('./components/ChapterContent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PopCatalog: typeof import('./components/PopCatalog.vue')['default']
    ReadSettings: typeof import('./components/ReadSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceDebug: typeof import('./components/SourceDebug.vue')['default']
    SourceHelp: typeof import('./components/SourceHelp.vue')['default']
    SourceItem: typeof import('./components/SourceItem.vue')['default']
    SourceJson: typeof import('./components/SourceJson.vue')['default']
    SourceList: typeof import('./components/SourceList.vue')['default']
    SourceTabForm: typeof import('./components/SourceTabForm.vue')['default']
    SourceTabTools: typeof import('./components/SourceTabTools.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
  }
}
